@startuml

interface CubeCell {
    summaryClass: string
    summaryLabel: TranslatableInterface
    coordinates: Coordinates
    measures: Measures
    measure: Measure
    sourceEntities: ?PageableInterface
    apex: CubeCell
    null: bool
    pivot(list): CubeCell
    rollUp(string|list): CubeCell
    drillDown(string|list): CubeCells
    slice(string, mixed): CubeCell
    find(string, mixed): ?CubeCell
    dice(?Expression): CubeCell
}

CubeCell *-- Coordinates
CubeCell *-- Measures
CubeCell *-- Measure
CubeCell o-- CubeCell

interface Dimension {
    name: string
    label: TranslatableInterface
    member: mixed
    rawMember: mixed
    displayMember: mixed
}

interface Measure {
    name: string
    label: TranslatableInterface
    value: mixed
    rawValue: mixed
    unit: ?Unit
}

interface Coordinates {
    summaryClass: string
    predicate: ?Expression
    dimensionality: <string>
}

Coordinates *--- Dimension

interface Measures {
}

Measures *--- Measure

@endu