@startuml

interface Result {
    summaryClass: string
    cube: CubeCell
}

Result *-- CubeCell

interface Cell {
    coordinates: Coordinates
    measures: Measures
    measure: Measure
    sourceEntities: ?PageableInterface
}

Cell *-- Coordinates
Cell *-- Measures
Cell *-- Measure

interface CubeCell {
    summaryClass: string
    apex: CubeCell
    null: bool
    rollUp(string): CubeCell
    drillDown(string): CubeCells
    slice(string, mixed): CubeCell
    find(string, mixed): ?CubeCell
    dice(?Expression): CubeCell
}

Cell <|- CubeCell
CubeCell o-- CubeCell

interface Dimension {
    name: string
    label: TranslatableInterface
    member: mixed
    rawMember: mixed
    displayMember: mixed
}

interface Measure {
    name: string
    label: TranslatableInterface
    value: mixed
    rawValue: mixed
    unit: ?Unit
}

interface Coordinates {
    summaryClass: string
    condition: ?Expression
    dimensionality: <string>
}

Coordinates *--- Dimension

interface Measures {
}

Measures *--- Measure

@endu