@startuml


json source {
    "coordinates": {
        "time.year":"2025",
        "country":"FR"
    }
    ,
    "measures": {
        "count": 6,
        "cost": 300
    }
}

json result {
    "coordinates": {
        "country":"FR",
        "time.year":"2025"
    }
    ,
    "measures": {
        "count": 6,
        "cost": 300
    }
}

source -> result : pivot("country", "time.year")


@endu