@startuml


json source {
    "coordinates": {
        "time.year":"2025",
        "country":"FR"
    }
    ,
    "measures": {
        "count": 6,
        "cost": 300
    }
}

json result {
    "coordinates": {
        "country":"FR"
    }
    ,
    "measures": {
        "count": 12,
        "cost": 450
    }
}

source -> result : rollUp("time.year")


@endu