@startuml

interface Result {
    summaryClass: string
    tree: TreeNode
}

Result o- TreeNode

interface Property {
    key: string
    label: TranslatableInterface
}

interface Dimension extends Property {
    member: mixed
    rawMember: mixed
    displayMember: mixed
}

interface TreeNode extends Dimension {
    summaryClass: class-string
    tuple: Tuple
    measure: ?Measure
    traverse(...$members): ?TreeNode
    null: bool
}

TreeNode o-- TreeNode

@endu