@startuml

hide empty members

class GroupBy {
}

GroupBy o-- GroupingSet
GroupBy o-- FieldSet
GroupBy o-- Field
GroupBy o-- Cube
GroupBy o-- RollUp

class GroupingSet {
}

GroupingSet o-- Cube
GroupingSet o-- RollUp
GroupingSet o-- FieldSet
GroupingSet o-- GroupingSet

class Cube {
}

Cube o-- Field

class RollUp {
}

RollUp o-- Field

class FieldSet {
}

Cube o- FieldSet
FieldSet o-- Field
FieldSet -o RollUp

class Field {
}



@enduml