@startuml

' Group

class TimeGroup {
    civil
    isoWeek
}

TimeGroup::civil o-- GregorianDateWithHour
TimeGroup::isoWeek o-- IsoWeekDateWithHour

' Systems

class GregorianDate {
    year
    quarter
    month
    date
}

GregorianDate::quarter o-- QuarterSet
GregorianDate::month o-- MonthSet
GregorianDate::date o-- DateSet

class GregorianDateWithHour {
    hour
}

GregorianDateWithHour --|> GregorianDate
GregorianDateWithHour o--- HourSet

class IsoWeekDate {
    weekYear
    week
    weekDate
}

IsoWeekDate::week o-- IsoWeekWeekSet
IsoWeekDate::weekDate o-- IsoWeekDateSet

class IsoWeekDateWithHour {
    hour
}

IsoWeekDateWithHour --|> IsoWeekDate
IsoWeekDateWithHour o--- HourSet

' Sets

class QuarterSet {
    quarter
    quarterOfYear
}

class MonthSet {
    month
    monthOfYear
}

class IsoWeekWeekSet {
    week
    weekOfYear
}

class DateSet {
    date
    dayOfWeek
    dayOfMonth
    dayOfYear
}

class IsoWeekDateSet {
    weekDate
    dayOfWeek
    dayOfWeekYear
}

class HourSet {
    hour
    hourOfDay
}


@enduml