@startuml
hide empty members

interface Cell {
}

Cell *- Coordinates

interface Coordinates {
}

class CoordinatesDto {
}

Cell --> CoordinatesDto : toDto()
Coordinates --> CoordinatesDto : toDto()
CoordinatesDto --> Cell : fromDto()