@startuml
interface AggregateFunction {
    getAggregateToResultExpression(string, SummaryQueryContext): string
}

interface SummarizableAggregateFunction extends AggregateFunction {
    getSourceToAggregateExpression(SourceQueryContext): string
    getAggregateToAggregateExpression(string): string
    getInvolvedProperties(): array;
}
@enduml