@startuml pivot-table

abstract Block {
    +getHeaderRows()
    +getDataRows()
    +getDataPaddingRows()
    +getSubtotalHeaderRows()
    +getSubtotalDataRows()
}

abstract BlockGroup {
    #getParentNode()
    #getChildBlocks()
    #getBalancedChildBlocks()
    #getOneChildBlock()
    #getOneBalancedChildBlock()
    #getChildren()
    #getBalancedChildren()
    #getOneChild()
}

Block <|-- BlockGroup
Block --o BlockGroup

class HorizontalBlockGroup {
}

BlockGroup <|-- HorizontalBlockGroup

class VerticalBlockGroup {
}

BlockGroup <|--- VerticalBlockGroup

class EmptyBlockGroup {
}

BlockGroup <|-- EmptyBlockGroup

abstract NodeBlock {
    +getTreeNode()
    +getParentBlock()
}

BlockGroup --o NodeBlock

abstract LeafBlock {
}

NodeBlock <|----- LeafBlock

class BranchBlock {
    +getChildrenBlockGroup()
}

NodeBlock <|-- BranchBlock
BlockGroup --o BranchBlock

Block <|----- NodeBlock

class NormalBlock {
}

BranchBlock <|-- NormalBlock

class NormalLeafBlock {
}

LeafBlock <|-- NormalLeafBlock

class PivotBlock {
}

BranchBlock <|-- PivotBlock

class PivotLeafBlock {
}

LeafBlock <|--- PivotLeafBlock

class RootBlock {
}

BranchBlock <|--- RootBlock

class EmptyBlock {
}

BranchBlock <|--- EmptyBlock

class SingleNodeLeafBlock {
}

LeafBlock <|-- SingleNodeLeafBlock

@enduml