@startuml pivot-table

abstract Block {
    #headerRows
    #dataRows
}

abstract BlockGroup {
    #children
    #balancedChildren
}

Block <|-- BlockGroup

class HorizontalBlockGroup {
}

BlockGroup <|-- HorizontalBlockGroup

class VerticalBlockGroup {
}

BlockGroup <|-- VerticalBlockGroup

abstract NodeBlock {
    #treeNode
}

Block <|---- NodeBlock

class NormalBlock {
}

NodeBlock <|-- NormalBlock

class NormalLeafBlock {
}

NodeBlock <|--- NormalLeafBlock

class PivotBlock {
}

NodeBlock <|---- PivotBlock

class PivotLeafBlock {
}

NodeBlock <|----- PivotLeafBlock

class RootBlock {
}

NodeBlock <|---- RootBlock

class EmptyBlock {
}

NodeBlock <|--- EmptyBlock

class SingleNodeLeafBlock {
}

NodeBlock <|-- SingleNodeLeafBlock

@enduml